"""Request and response schemas for the API."""

from __future__ import annotations
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# ============ Common Enums ============

class PairingAlgorithmEnum(str, Enum):
    SWISS = "swiss"
    MCMAHON = "mcmahon"


class GameResultEnum(str, Enum):
    BLACK_WIN = "B+"
    WHITE_WIN = "W+"
    BLACK_WIN_FORFEIT = "B+F"
    WHITE_WIN_FORFEIT = "W+F"
    DRAW = "Draw"
    NO_RESULT = "NR"
    BOTH_LOSE = "BL"


class HandicapTypeEnum(str, Enum):
    NONE = "none"
    RANK_DIFFERENCE = "rank_difference"


class HandicapModifierEnum(str, Enum):
    NONE = "none"
    MINUS_1 = "minus_1"
    MINUS_2 = "minus_2"


# ============ Player Schemas ============

class PlayerInput(BaseModel):
    """Player data for pairing/standings requests."""
    id: str
    name: str
    rank: str = Field(..., pattern=r"^\d+[kdKD]$", description="Go rank like '5k' or '3d'")
    club: Optional[str] = None
    aga_id: Optional[str] = None
    rating: Optional[float] = None
    rounds_participating: list[int] = Field(default_factory=list)
    initial_mcmahon_score: Optional[int] = None


class PlayerOutput(BaseModel):
    """Player in response."""
    id: str
    name: str
    rank: str


# ============ Pairing Schemas ============

class PairingInput(BaseModel):
    """Existing pairing from a completed round."""
    black_player_id: str
    white_player_id: str
    result: GameResultEnum


class ByeInput(BaseModel):
    """Existing bye from a completed round."""
    player_id: str
    points: float = 1.0


class RoundInput(BaseModel):
    """Historical round data."""
    number: int
    pairings: list[PairingInput] = Field(default_factory=list)
    byes: list[ByeInput] = Field(default_factory=list)


class PairingOutput(BaseModel):
    """Generated pairing."""
    black_player_id: str
    white_player_id: str
    board_number: int
    handicap_stones: int
    komi: float


class ByeOutput(BaseModel):
    """Generated bye."""
    player_id: str
    points: float


class PairingRequest(BaseModel):
    """Request to generate pairings for a round."""
    players: list[PlayerInput]
    previous_rounds: list[RoundInput] = Field(default_factory=list)
    round_number: int = Field(..., ge=1)
    algorithm: PairingAlgorithmEnum = PairingAlgorithmEnum.MCMAHON
    mcmahon_bar: Optional[str] = Field(None, pattern=r"^\d+[kdKD]$")
    handicap_type: HandicapTypeEnum = HandicapTypeEnum.RANK_DIFFERENCE
    handicap_modifier: HandicapModifierEnum = HandicapModifierEnum.NONE


class PairingResponse(BaseModel):
    """Response with generated pairings."""
    pairings: list[PairingOutput]
    byes: list[ByeOutput]
    warnings: list[str]


# ============ Standings Schemas ============

class StandingsRequest(BaseModel):
    """Request to calculate standings."""
    players: list[PlayerInput]
    rounds: list[RoundInput]
    through_round: Optional[int] = Field(None, ge=1)


class PlayerStandingOutput(BaseModel):
    """Single player's standing."""
    rank: int
    player_id: str
    player_name: str
    player_rank: str
    wins: float
    losses: float
    sos: float
    sds: float
    sosos: float


class StandingsResponse(BaseModel):
    """Response with calculated standings."""
    standings: list[PlayerStandingOutput]


# ============ Handicap Schemas ============

class HandicapRequest(BaseModel):
    """Request to calculate handicap for a game."""
    white_rank: str = Field(..., pattern=r"^\d+[kdKD]$")
    black_rank: str = Field(..., pattern=r"^\d+[kdKD]$")
    handicap_type: HandicapTypeEnum = HandicapTypeEnum.RANK_DIFFERENCE
    handicap_modifier: HandicapModifierEnum = HandicapModifierEnum.NONE


class HandicapResponse(BaseModel):
    """Calculated handicap."""
    stones: int
    komi: float
    description: str


# ============ Validation Schemas ============

class RankValidationRequest(BaseModel):
    """Request to validate rank strings."""
    ranks: list[str]


class RankValidationResult(BaseModel):
    """Validation result for a single rank."""
    rank: str
    valid: bool
    normalized: Optional[str] = None
    error: Optional[str] = None


class RankValidationResponse(BaseModel):
    """Response with validation results."""
    results: list[RankValidationResult]
    all_valid: bool


# ============ Health Check ============

class HealthResponse(BaseModel):
    """Health check response."""
    status: str
    version: str
