import type { Player, Tournament, PlayerStanding } from '@/types';

// Sample players
export const mockPlayers: Player[] = [
  {
    id: 'p1',
    name: 'Alice Chen',
    rank: '5d',
    club: 'NYC Go Club',
    agaId: '12345',
    rating: 2100,
    email: 'alice@example.com',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'p2',
    name: 'Bob Kim',
    rank: '3d',
    club: 'Brooklyn Go',
    agaId: '12346',
    rating: 1900,
    email: 'bob@example.com',
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'p3',
    name: 'Carol Wang',
    rank: '1d',
    club: 'NYC Go Club',
    agaId: '12347',
    rating: 1700,
    createdAt: '2024-01-17T10:00:00Z',
    updatedAt: '2024-01-17T10:00:00Z',
  },
  {
    id: 'p4',
    name: 'David Lee',
    rank: '2k',
    club: 'Queens Go',
    agaId: '12348',
    rating: 1500,
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    id: 'p5',
    name: 'Eva Martinez',
    rank: '5k',
    club: 'Brooklyn Go',
    agaId: '12349',
    rating: 1200,
    createdAt: '2024-01-19T10:00:00Z',
    updatedAt: '2024-01-19T10:00:00Z',
  },
  {
    id: 'p6',
    name: 'Frank Zhang',
    rank: '8k',
    club: 'NYC Go Club',
    agaId: '12357',
    rating: 900,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'p7',
    name: 'Grace Park',
    rank: '4d',
    club: 'Manhattan Go',
    agaId: '12350',
    rating: 2000,
    createdAt: '2024-01-21T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
  },
  {
    id: 'p8',
    name: 'Henry Liu',
    rank: '2d',
    club: 'Queens Go',
    agaId: '12351',
    rating: 1800,
    createdAt: '2024-01-22T10:00:00Z',
    updatedAt: '2024-01-22T10:00:00Z',
  },
  {
    id: 'p9',
    name: 'Isabelle Tanaka',
    rank: '6d',
    club: 'Manhattan Go',
    agaId: '12352',
    rating: 2200,
    email: 'isabelle@example.com',
    createdAt: '2024-01-23T10:00:00Z',
    updatedAt: '2024-01-23T10:00:00Z',
  },
  {
    id: 'p10',
    name: 'James Wu',
    rank: '1k',
    club: 'NYC Go Club',
    agaId: '12353',
    rating: 1600,
    createdAt: '2024-01-24T10:00:00Z',
    updatedAt: '2024-01-24T10:00:00Z',
  },
  {
    id: 'p11',
    name: 'Kevin Patel',
    rank: '3k',
    club: 'Queens Go',
    agaId: '12354',
    rating: 1400,
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-01-25T10:00:00Z',
  },
  {
    id: 'p12',
    name: 'Laura Hoffman',
    rank: '7k',
    club: 'Brooklyn Go',
    agaId: '12355',
    rating: 1000,
    email: 'laura@example.com',
    createdAt: '2024-01-26T10:00:00Z',
    updatedAt: '2024-01-26T10:00:00Z',
  },
  {
    id: 'p13',
    name: "Michael O'Brien",
    rank: '10k',
    club: 'NYC Go Club',
    agaId: '12356',
    rating: 700,
    createdAt: '2024-01-27T10:00:00Z',
    updatedAt: '2024-01-27T10:00:00Z',
  },
  {
    id: 'p14',
    name: 'Nina Sokolov',
    rank: '12k',
    club: 'Manhattan Go',
    agaId: '12358',
    rating: 500,
    createdAt: '2024-01-28T10:00:00Z',
    updatedAt: '2024-01-28T10:00:00Z',
  },
  {
    id: 'p15',
    name: 'Oscar Rivera',
    rank: '15k',
    club: 'Brooklyn Go',
    agaId: '12359',
    rating: 300,
    createdAt: '2024-01-29T10:00:00Z',
    updatedAt: '2024-01-29T10:00:00Z',
  },
];

// Sample tournaments
export const mockTournaments: Tournament[] = [
  {
    id: 't1',
    name: 'NYIG Winter Championship 2024',
    description: 'Annual winter tournament for all skill levels',
    date: '2024-02-15',
    location: 'NYC Go Club, Manhattan',
    status: 'in_progress',
    settings: {
      numRounds: 4,
      pairingAlgorithm: 'mcmahon',
      handicapType: 'rank_difference',
      handicapModifier: 'minus_1',
      mcmahonBar: '3d',
      crossDivisionPairing: true,
      tiebreakerOrder: ['wins', 'sos', 'sds', 'hth'],
    },
    divisions: [
      { id: 'div-dan', name: 'Dan Section', description: '1d and above' },
      { id: 'div-kyu', name: 'Kyu Section', description: 'All kyu players' },
    ],
    registrations: [
      { playerId: mockPlayers[0], divisionId: 'div-dan', roundsParticipating: [], registeredAt: '2024-02-01T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[1], divisionId: 'div-dan', roundsParticipating: [], registeredAt: '2024-02-01T11:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[2], divisionId: 'div-dan', roundsParticipating: [], registeredAt: '2024-02-02T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[3], divisionId: 'div-kyu', roundsParticipating: [], registeredAt: '2024-02-02T14:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[4], divisionId: 'div-kyu', roundsParticipating: [], registeredAt: '2024-02-03T09:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[5], divisionId: 'div-kyu', roundsParticipating: [], registeredAt: '2024-02-03T15:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[6], divisionId: 'div-dan', roundsParticipating: [], registeredAt: '2024-02-04T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[7], divisionId: 'div-dan', roundsParticipating: [], registeredAt: '2024-02-04T14:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[8], divisionId: 'div-dan', roundsParticipating: [], registeredAt: '2024-02-05T09:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[9], divisionId: 'div-kyu', roundsParticipating: [], registeredAt: '2024-02-05T11:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[10], divisionId: 'div-kyu', roundsParticipating: [], registeredAt: '2024-02-05T14:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[11], divisionId: 'div-kyu', roundsParticipating: [], registeredAt: '2024-02-06T09:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[12], divisionId: 'div-kyu', roundsParticipating: [1, 2, 3], registeredAt: '2024-02-06T11:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[13], divisionId: 'div-kyu', roundsParticipating: [1, 2], registeredAt: '2024-02-06T14:00:00Z', withdrawn: false, checkedIn: false },
    ],
    rounds: [
      {
        number: 1,
        status: 'completed',
        pairings: [
          { blackPlayerId: 'p1', whitePlayerId: 'p2', boardNumber: 1, handicapStones: 0, komi: 6.5, result: 'black_wins' },
          { blackPlayerId: 'p3', whitePlayerId: 'p8', boardNumber: 2, handicapStones: 0, komi: 6.5, result: 'white_wins' },
          { blackPlayerId: 'p4', whitePlayerId: 'p10', boardNumber: 3, handicapStones: 0, komi: 6.5, result: 'black_wins' },
          { blackPlayerId: 'p5', whitePlayerId: 'p6', boardNumber: 4, handicapStones: 3, komi: 0.5, result: 'black_wins' },
          { blackPlayerId: 'p11', whitePlayerId: 'p12', boardNumber: 5, handicapStones: 4, komi: 0.5, result: 'white_wins' },
          { blackPlayerId: 'p13', whitePlayerId: 'p14', boardNumber: 6, handicapStones: 2, komi: 0.5, result: 'black_wins' },
          { blackPlayerId: 'p9', whitePlayerId: 'p7', boardNumber: 7, handicapStones: 0, komi: 6.5, result: 'black_wins' },
        ],
        byes: [],
        pairedAt: '2024-02-15T09:00:00Z',
        completedAt: '2024-02-15T12:00:00Z',
      },
      {
        number: 2,
        status: 'paired',
        pairings: [
          { blackPlayerId: 'p1', whitePlayerId: 'p9', boardNumber: 1, handicapStones: 0, komi: 6.5, result: 'no_result' },
          { blackPlayerId: 'p4', whitePlayerId: 'p8', boardNumber: 2, handicapStones: 3, komi: 0.5, result: 'no_result' },
          { blackPlayerId: 'p5', whitePlayerId: 'p13', boardNumber: 3, handicapStones: 5, komi: 0.5, result: 'no_result' },
          { blackPlayerId: 'p12', whitePlayerId: 'p2', boardNumber: 4, handicapStones: 0, komi: 6.5, result: 'no_result' },
          { blackPlayerId: 'p7', whitePlayerId: 'p3', boardNumber: 5, handicapStones: 0, komi: 6.5, result: 'no_result' },
          { blackPlayerId: 'p14', whitePlayerId: 'p10', boardNumber: 6, handicapStones: 0, komi: 6.5, result: 'no_result' },
          { blackPlayerId: 'p6', whitePlayerId: 'p11', boardNumber: 7, handicapStones: 5, komi: 0.5, result: 'no_result' },
        ],
        byes: [],
        pairedAt: '2024-02-15T13:00:00Z',
      },
      { number: 3, status: 'pending', pairings: [], byes: [] },
      { number: 4, status: 'pending', pairings: [], byes: [] },
    ],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-02-15T13:00:00Z',
  },
  {
    id: 't2',
    name: 'Brooklyn Open 2024',
    description: 'Open tournament at Brooklyn Go Club',
    date: '2024-03-10',
    location: 'Brooklyn Go Club',
    status: 'setup',
    settings: {
      numRounds: 3,
      pairingAlgorithm: 'swiss',
      handicapType: 'none',
      handicapModifier: 'none',
      crossDivisionPairing: true,
      tiebreakerOrder: ['wins', 'sos', 'sds', 'hth'],
    },
    divisions: [
      { id: 'div-open', name: 'Open', description: 'All ranks welcome' },
      { id: 'div-beginner', name: 'Beginner', description: '10k and below' },
    ],
    registrations: [
      { playerId: mockPlayers[6], divisionId: 'div-open', roundsParticipating: [], registeredAt: '2024-02-20T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[7], divisionId: 'div-open', roundsParticipating: [], registeredAt: '2024-02-21T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[10], divisionId: 'div-open', roundsParticipating: [], registeredAt: '2024-02-22T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[11], divisionId: 'div-open', roundsParticipating: [], registeredAt: '2024-02-22T14:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[13], divisionId: 'div-beginner', roundsParticipating: [], registeredAt: '2024-02-23T10:00:00Z', withdrawn: false, checkedIn: false },
      { playerId: mockPlayers[14], divisionId: 'div-beginner', roundsParticipating: [], registeredAt: '2024-02-23T14:00:00Z', withdrawn: false, checkedIn: false },
    ],
    rounds: [
      { number: 1, status: 'pending', pairings: [], byes: [] },
      { number: 2, status: 'pending', pairings: [], byes: [] },
      { number: 3, status: 'pending', pairings: [], byes: [] },
    ],
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-02-23T14:00:00Z',
  },
  {
    id: 't3',
    name: 'Fall Classic 2023',
    date: '2023-10-20',
    location: 'Manhattan Go Center',
    status: 'completed',
    settings: {
      numRounds: 4,
      pairingAlgorithm: 'mcmahon',
      handicapType: 'rank_difference',
      handicapModifier: 'none',
      mcmahonBar: '4d',
      crossDivisionPairing: true,
      tiebreakerOrder: ['wins', 'sos', 'sds', 'hth'],
    },
    divisions: [],
    registrations: [],
    rounds: [
      { number: 1, status: 'completed', pairings: [], byes: [] },
      { number: 2, status: 'completed', pairings: [], byes: [] },
      { number: 3, status: 'completed', pairings: [], byes: [] },
      { number: 4, status: 'completed', pairings: [], byes: [] },
    ],
    createdAt: '2023-09-15T10:00:00Z',
    updatedAt: '2023-10-20T18:00:00Z',
  },
];

// Sample standings for tournament t1
export const mockStandings: Record<string, PlayerStanding[]> = {
  t1: [
    { rank: 1, playerId: 'p9', playerName: 'Isabelle Tanaka', playerRank: '6d', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 2, playerId: 'p1', playerName: 'Alice Chen', playerRank: '5d', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 3, playerId: 'p4', playerName: 'David Lee', playerRank: '2k', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 4, playerId: 'p5', playerName: 'Eva Martinez', playerRank: '5k', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 5, playerId: 'p8', playerName: 'Henry Liu', playerRank: '2d', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 6, playerId: 'p12', playerName: 'Laura Hoffman', playerRank: '7k', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 7, playerId: 'p13', playerName: "Michael O'Brien", playerRank: '10k', wins: 1, losses: 0, sos: 0, sds: 0, sosos: 0 },
    { rank: 8, playerId: 'p2', playerName: 'Bob Kim', playerRank: '3d', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
    { rank: 9, playerId: 'p3', playerName: 'Carol Wang', playerRank: '1d', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
    { rank: 10, playerId: 'p6', playerName: 'Frank Zhang', playerRank: '8k', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
    { rank: 11, playerId: 'p7', playerName: 'Grace Park', playerRank: '4d', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
    { rank: 12, playerId: 'p10', playerName: 'James Wu', playerRank: '1k', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
    { rank: 13, playerId: 'p11', playerName: 'Kevin Patel', playerRank: '3k', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
    { rank: 14, playerId: 'p14', playerName: 'Nina Sokolov', playerRank: '12k', wins: 0, losses: 1, sos: 1, sds: 0, sosos: 0 },
  ],
  t2: [],
  t3: [],
};
